dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "9"
install:
  - npm install -g truffle
  - npm install -g ethereumjs-testrpc
  - npm install --save-dev solidity-coverage
  - npm install
before_script:
  - npm run gana
  - sleep
script:
  - truffle test
